{
  "comments": [
    {
      "key": {
        "uuid": "0c74357b_b3e33b23",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 14,
      "author": {
        "id": 1041833
      },
      "writtenOn": "2018-10-05T15:11:36Z",
      "side": 1,
      "message": "Test: ...\n\nThere are native_heapdump_viewer_tests.",
      "revId": "aa08d5aa3736e0b50d0035cccd9ec7c28ae98c07",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "3f445427_5d0f984b",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 14,
      "author": {
        "id": 1105104
      },
      "writtenOn": "2018-10-05T16:33:47Z",
      "side": 1,
      "message": "I ran the test, but it seems to be broken. I see that https://android-review.googlesource.com/c/platform/development/+/724065 extended ParseNativeHeap() by one more argument but the tests haven\u0027t been updated to reflect that.\n\n$ python heapdump_viewer_tests.py\n\n....EEEE\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nERROR: test_backtrace_num_field_invalid (__main__.ParseNativeHeapTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"native_heapdump_viewer_tests.py\", line 127, in test_backtrace_num_field_invalid\n    backtraces, mapppings \u003d native_heapdump_viewer.ParseNativeHeap(heap, False, False)\nTypeError: ParseNativeHeap() takes exactly 4 arguments (3 given)\n\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nERROR: test_backtrace_num_field_valid (__main__.ParseNativeHeapTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"native_heapdump_viewer_tests.py\", line 111, in test_backtrace_num_field_valid\n    backtraces, mapppings \u003d native_heapdump_viewer.ParseNativeHeap(heap, False, True)\nTypeError: ParseNativeHeap() takes exactly 4 arguments (3 given)\n\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nERROR: test_backtrace_reverse_field_valid (__main__.ParseNativeHeapTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"native_heapdump_viewer_tests.py\", line 143, in test_backtrace_reverse_field_valid\n    backtraces, mapppings \u003d native_heapdump_viewer.ParseNativeHeap(heap, True, True)\nTypeError: ParseNativeHeap() takes exactly 4 arguments (3 given)\n\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nERROR: test_mappings (__main__.ParseNativeHeapTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"native_heapdump_viewer_tests.py\", line 167, in test_mappings\n    backtraces, mappings \u003d native_heapdump_viewer.ParseNativeHeap(heap, True, True)\nTypeError: ParseNativeHeap() takes exactly 4 arguments (3 given)\n\n----------------------------------------------------------------------\nRan 8 tests in 0.001s\n\nFAILED (errors\u003d4)\nshibing@shibing-linux:/local/mnt/workspace/shibing/temp/aospmaster/development/sc",
      "parentUuid": "0c74357b_b3e33b23",
      "revId": "aa08d5aa3736e0b50d0035cccd9ec7c28ae98c07",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "c5f2adbe_dd775ab3",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 14,
      "author": {
        "id": 1105104
      },
      "writtenOn": "2018-10-05T16:44:03Z",
      "side": 1,
      "message": "If I pass \"\" as the 4th arg in ParseNativeHeap()  from the test, the tests pass:\n\n$ python native_heapdump_viewer_tests.py\n........\n----------------------------------------------------------------------\nRan 8 tests in 0.002s\n\nOK",
      "parentUuid": "3f445427_5d0f984b",
      "revId": "aa08d5aa3736e0b50d0035cccd9ec7c28ae98c07",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "0f632ce3_d64b96db",
        "filename": "scripts/native_heapdump_viewer.py",
        "patchSetId": 2
      },
      "lineNbr": 330,
      "author": {
        "id": 1041833
      },
      "writtenOn": "2018-10-05T15:08:36Z",
      "side": 1,
      "message": "I think there needs to be a stronger indication of the crash.",
      "range": {
        "startLine": 330,
        "startChar": 66,
        "endLine": 330,
        "endChar": 78
      },
      "revId": "aa08d5aa3736e0b50d0035cccd9ec7c28ae98c07",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "67b9fc6b_198f8099",
        "filename": "scripts/native_heapdump_viewer.py",
        "patchSetId": 2
      },
      "lineNbr": 330,
      "author": {
        "id": 1105104
      },
      "writtenOn": "2018-10-05T16:35:25Z",
      "side": 1,
      "message": "printed the return code of addr2line and loggin an exception as well (will be logged to stderr so no worries with --html as well)",
      "parentUuid": "0f632ce3_d64b96db",
      "range": {
        "startLine": 330,
        "startChar": 66,
        "endLine": 330,
        "endChar": 78
      },
      "revId": "aa08d5aa3736e0b50d0035cccd9ec7c28ae98c07",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}